version: '1'

services:
  dev:
    build: 
      context: .
      dockerfile: dev.Dockerfile
      args:
        ENVIRONMENT: dev
        FLASK_ENV: development
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./:/app
      - /Users/jbshah/_p/storage/drone_file_server:/app/backend_storage:ro
    environment:
      ENVIRONMENT: dev
    profiles:
      - dev
  
  # In case we need to separate the storage locker service
  # storage-locker-dev:
  #   image: node:22-slim
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /Users/jbshah/_p/storage/drone_file_server:/app/backend_storage/flights:ro
  #   command: npx http-server /app/backend_storage/flights --cors -p 8080
  #   profiles:
  #     - dev

  prod:
    build: 
      context: .
      dockerfile: dev.Dockerfile
      platforms:
        - "linux/amd64"
      args:
        ENVIRONMENT: prod
        STORAGE_PATH: /cals-research-station
    volumes:
      - ./:/app
      - /cals-research-station:/app/backend_storage:ro
    ports:
      - "5000:5000"
    # environment:
    #   ENVIRONMENT: prod
    #   FLASK_ENV: production
    networks:
      - drone-network
    profiles:
      - prod

networks:
  drone-network:
    name: drone-network