# MANAGED BY MANUAL CONFIG
server {
    listen 80;
    listen [::]:80;
    server_name dronepilotapp.psi.ncsu.edu;
    client_max_body_size 100M;
    # Access and error logs
    access_log /var/log/nginx/dronepilotapp.psi.ncsu.edu.access.log;
    error_log /var/log/nginx/dronepilotapp.psi.ncsu.edu.error.log;

    # Proxy to the frontend Docker container
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # API endpoints - proxy directly to the API container
    # location ~ ^/(ping|flight-list|set-grid/.*) {
    #     include proxy_params;
    #     proxy_pass http://127.0.0.1:5000;
    #     # proxy_set_header Host $host;
    #     # proxy_set_header X-Real-IP $remote_addr;
    #     # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # }
    location /ping {
        include proxy_params;
        proxy_pass http://localhost:5000;
    }
    location /flight-list {
        include proxy_params;
        proxy_pass http://localhost:5000;
    }
    location /set-grid {
        include proxy_params;
        proxy_pass http://localhost:5000;
    }
    
    # File server - proxy to the file server container
    location /data {
        proxy_pass http://localhost:8080;
        rewrite ^/data(.*) $1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}